# Hito 4 — Fixture 2030 — Módulo documental de equipos y jugadores (MongoDB)
services:
  mongodb:
    image: mongo:latest
    container_name: fixture2030-mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ${HOME}/docker/data/mongodb:/data/db     # persistencia (RF2)
      - ./scripts:/scripts:ro
      - ./data:/data/import:ro
